name: Test Build
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Project
        uses: actions/checkout@v3
      - name: Install Deps For Client
        run: npm install --prefix client
      - name: Install Deps For Server
        run: npm install --prefix server
      - name: Build Client
        run: npm run build --prefix client
      - name: Build Server
        run: npm run build --prefix server
